# Base image: Nginx Docker hub image at tag 1.19
YOUR CODE HERE

# Copy nginx.conf file from config folder on Context to /etc/nginx/nginx.conf
YOUR CODE HERE

# Copy site folder from on Context to /var/www
YOUR CODE HERE

# The Nginx base image already has a valid CMD so no further changes are needed
