# First step - Generate build
# From node 15.14 image as app-builder
YOUR CODE HERE

# Create a /app-build folder to work in
YOUR CODE HERE
# Set /app-build as workdir
YOUR CODE HERE

# Copy src and public folders into the workdir folder
YOUR CODE HERE
YOUR CODE HERE
# Copy package.json and package-lock.json files into the workdir folder
YOUR CODE HERE
YOUR CODE HERE

# Install project NPM dependencies
YOUR CODE HERE
# Build project (Build is generated on a build folder)
YOUR CODE HERE

# Second step - Create app from build
# From node 15.14-alpine image as app
YOUR CODE HERE

# Install serve as global dependency (Used to serve site) using npm
YOUR CODE HERE

# Create a /app folder to work in
YOUR CODE HERE
# Set /app as workdir
YOUR CODE HERE

# Copy build folder from the app-builder image
YOUR CODE HERE

# Command to run the app from the app folder
YOUR CODE HERE
