version: "3.4"

services:

    nginx: # Nginx container definition
        image: nginx:latest # Use latest nginx image
        ports: # Expose port 80
            - "80:80"
        volumes: # Mount files on the clean Nginx image
            - ./site:/site  # Mount site folder on path /site for the container
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf # Add Nginx config on /etc/nginx/conf.d/default.conf

    php: # PHP container definition
        image: php:8.0-fpm # Use php fpm version 8.0 as image
        volumes: # Mount files on the clean PHP image
            - ./site:/site # Mount site folder on path /site for the container
