version: "3.4"

services:

    nginx: # Nginx container definition
        image: nginx:latest # Use latest nginx image
        ports: # Expose port 80
            - "80:80"
        volumes: # Mount files on the clean Nginx image
            - ./site:/site # Mount site folder on path /site for the container
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf # Add Nginx config on /etc/nginx/conf.d/default.conf

    php: # PHP container definition
        image: exercise5_2-php:latest # Use custom exercise4_2-php image

    mysql: # MySQL container definition
        image: mysql:5.7 # Use 5.7 mysql image
        ports: # Expose port 3306 to access mysql from outside the containers
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test-db
