# VARIABLE DEFINITIONS
TO_BE_FILLED

# HELPERS
COMPOSE = \
	TO_BE_FILLED

# MAIN COMMANDS

# Start command
start:
	TO_BE_FILLED
	TO_BE_FILLED
	TO_BE_FILLED
	echo "Visit site on http://localhost"

# Stop command
stop:
	TO_BE_FILLED

# Reset quotations command
reset-quotations:
	$(COMPOSE) exec php mysql -h mysql -u root --password=root -e "truncate \`test-table\`" test-db

# Bash on PHP container command
php-bash:
	TO_BE_FILLED
